### ISSUE TITLE
Update demo source - VKI_sizeAdj parameter

### ISSUE THREAD

**Issue by defacto133** [the-darc/angular-virtual-keyboard#13]
1. The demo source uses `VKI_CONFIG.VKI_i18n` instead of `VKI_CONFIG.i18n`.
2. I think there should be a parameter for `VKI_sizeAdj` because now it's just set to `true` if I'm not missing something.

**Comment by the-darc** [comment]
1. Fixed in branch master an will be merged in the next release.
2. You aren't missing nothing. The `VKI_sizeAdj` is a configuration of the [greywyvern VKI](http://www.greywyvern.com/code/javascript/keyboard) and wasn't exposed by the _angular-virtual-keyboard_ because it wasn't priorized until now. At some moment I intend to review all the configurations of _greywyvern VKI_ and expose them. But, if you need it, fell free to expose this parameter and send us a pull request.

I will be glad to merge any contribution in this repository!

Thanks!

**Comment by the-darc** [comment]
solved in version 0.4.2

**Comment by defacto133** [comment]
Thank you :)
